import { Quest, Spark, FamilyMember } from './types';

export const SAMPLE_QUESTS: Quest[] = [
  {
    id: '1',
    title: 'The Secret Kindness',
    description: 'Do something helpful for someone in your family without telling them. See if they notice.',
    domain: 'others',
    action: 'do',
    tier: 'explorer',
    timeEstimate: '15 min',
    icon: '💝',
  },
  {
    id: '2', 
    title: 'Emotion Detective',
    description: 'Notice every time you feel frustrated today. What triggered it? Keep a mental tally.',
    domain: 'self',
    action: 'look',
    tier: 'explorer',
    timeEstimate: 'All day',
    icon: '🔍',
  },
  {
    id: '3',
    title: 'The Stillness Challenge',
    description: 'Sit outside for 5 minutes. Don\'t do anything. Just notice what you see, hear, and feel.',
    domain: 'wonder',
    action: 'look',
    tier: 'explorer',
    timeEstimate: '5 min',
    icon: '🧘',
  },
  {
    id: '4',
    title: 'Game Inventor',
    description: 'Create a brand new game with rules. Then teach it to someone and play together.',
    domain: 'play',
    action: 'do',
    tier: 'explorer',
    timeEstimate: '30 min',
    icon: '🎲',
  },
  {
    id: '5',
    title: 'How Things Work',
    description: 'Pick something in your house you use every day. Find out how it actually works inside.',
    domain: 'world',
    action: 'think',
    tier: 'explorer',
    timeEstimate: '20 min',
    icon: '⚙️',
  },
];

export const SAMPLE_SPARKS: Spark[] = [
  {
    id: '1',
    text: 'The beginning of wisdom is silence. The second stage is listening.',
    source: 'Hebrew Proverb',
    domain: 'others',
    unlocked: true,
    unlockedAt: new Date('2026-02-08'),
  },
  {
    id: '2',
    text: 'Know yourself. Love yourself. Be true to yourself.',
    source: 'Family Wisdom',
    domain: 'self',
    unlocked: true,
    unlockedAt: new Date('2026-02-06'),
  },
  {
    id: '3',
    text: 'Those who say yes are rewarded by adventures. Those who say no are rewarded by safety.',
    source: 'Family Wisdom',
    domain: 'play',
    unlocked: true,
    unlockedAt: new Date('2026-02-04'),
  },
  {
    id: '4',
    text: 'Mistakes are gifts. They show you something true about the world.',
    source: 'Modern Wisdom',
    domain: 'world',
    unlocked: false,
  },
  {
    id: '5',
    text: 'The most beautiful thing we can experience is the mysterious.',
    source: 'Albert Einstein',
    domain: 'wonder',
    unlocked: false,
  },
];

export const SAMPLE_FAMILY: FamilyMember[] = [
  {
    id: '1',
    name: 'Alex',
    avatar: '👨',
    age: 38,
    tier: 'navigator',
    role: 'parent',
  },
  {
    id: '2',
    name: 'Maya',
    avatar: '👩',
    age: 36,
    tier: 'navigator',
    role: 'parent',
  },
  {
    id: '3',
    name: 'Lily',
    avatar: '👧',
    age: 9,
    tier: 'explorer',
    role: 'child',
  },
  {
    id: '4',
    name: 'Sam',
    avatar: '👦',
    age: 7,
    tier: 'seedling',
    role: 'child',
  },
];
